#!/bin/bash

# Ship Framework — Setup
# Zero-prompt install. Copies files, installs Playwright. That's it.
# All product context (name, description, stack) is gathered by /team on first run.
#
# Usage:
#   bash ship-framework/setup.sh              # sets up in current directory
#   bash ship-framework/setup.sh ./my-project  # sets up in specified directory

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE_DIR="$SCRIPT_DIR/template"
VERSION=$(cat "$SCRIPT_DIR/VERSION" 2>/dev/null || echo "unknown")

# Colors
BOLD='\033[1m'
DIM='\033[2m'
ORANGE='\033[38;5;208m'
GREEN='\033[32m'
YELLOW='\033[33m'
RESET='\033[0m'

echo ""
echo -e "${BOLD}${ORANGE}Ship Framework${RESET} v${VERSION} — Setup"
echo ""

# ─── Target directory ─────────────────────────────────────────────────────
# Accept as argument or default to current directory

if [ -n "$1" ]; then
  TARGET_DIR="$1"
else
  TARGET_DIR="."
fi

# Resolve to absolute path
TARGET_DIR="$(cd "$TARGET_DIR" 2>/dev/null && pwd)" || {
  echo "Error: Directory not found: $TARGET_DIR"
  exit 1
}

# ─── Check for existing CLAUDE.md ─────────────────────────────────────────

if [ -f "$TARGET_DIR/CLAUDE.md" ]; then
  if grep -q "## /team" "$TARGET_DIR/CLAUDE.md" 2>/dev/null; then
    # Previous Ship Framework install — safe to update
    echo -e "${DIM}Found existing Ship Framework CLAUDE.md. Updating commands and references.${RESET}"
    echo ""

    # Update commands
    mkdir -p "$TARGET_DIR/.claude/commands"
    cp "$TEMPLATE_DIR/.claude/commands/"*.md "$TARGET_DIR/.claude/commands/"
    echo -e "${GREEN}✓${RESET} Updated .claude/commands/"

    # Update references (never overwrite user's design-system.md)
    if [ -d "$TEMPLATE_DIR/references" ]; then
      mkdir -p "$TARGET_DIR/references"
      for ref_file in "$TEMPLATE_DIR/references/"*.md; do
        filename=$(basename "$ref_file")
        if [ "$filename" = "design-system.md" ] && [ -f "$TARGET_DIR/references/design-system.md" ]; then
          continue
        fi
        cp "$ref_file" "$TARGET_DIR/references/$filename"
      done
      echo -e "${GREEN}✓${RESET} Updated references/"
    fi

    # Update cheatsheet
    cp "$SCRIPT_DIR/CHEATSHEET.md" "$TARGET_DIR/CHEATSHEET.md"
    echo -e "${GREEN}✓${RESET} Updated CHEATSHEET.md"

    # Create DECISIONS.md and CONTEXT.md if missing
    if [ ! -f "$TARGET_DIR/DECISIONS.md" ] && [ -f "$TEMPLATE_DIR/DECISIONS.md" ]; then
      cp "$TEMPLATE_DIR/DECISIONS.md" "$TARGET_DIR/DECISIONS.md"
      echo -e "${GREEN}✓${RESET} Created DECISIONS.md (new in this version)"
    fi
    if [ ! -f "$TARGET_DIR/CONTEXT.md" ] && [ -f "$TEMPLATE_DIR/CONTEXT.md" ]; then
      cp "$TEMPLATE_DIR/CONTEXT.md" "$TARGET_DIR/CONTEXT.md"
      echo -e "${GREEN}✓${RESET} Created CONTEXT.md (new in this version)"
    fi

    # Stamp version
    if grep -q "Generated by \[Ship Framework\]" "$TARGET_DIR/CLAUDE.md" 2>/dev/null; then
      sed -i "s/v[0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\}/v${VERSION}/" "$TARGET_DIR/CLAUDE.md"
    fi

    echo ""
    echo -e "${BOLD}${ORANGE}Updated!${RESET} Commands, references, and cheatsheet are current."
    echo ""
    exit 0
  else
    # Their own CLAUDE.md — append mode
    echo -e "${YELLOW}⚠${RESET}  Found existing CLAUDE.md (not from Ship Framework)."
    echo -e "${DIM}Ship Framework will append to your existing file, not replace it.${RESET}"
    echo ""
  fi
fi

# ─── Generate CLAUDE.md (no prompts — placeholders for /team) ─────────────

PRODUCT_NAME="<!-- SHIP_SETUP: product name not set -->"
PRODUCT_DESC="<!-- SHIP_SETUP: product description not set -->"
STACK_BULLETS="<!-- SHIP_SETUP: tech stack not set -->"

if [ -f "$TARGET_DIR/CLAUDE.md" ]; then
  # Append Ship Framework to existing CLAUDE.md
  python3 << 'PYEOF' - "$TEMPLATE_DIR/CLAUDE.md" "$TARGET_DIR/CLAUDE.md" "$PRODUCT_NAME" "$PRODUCT_DESC" "$STACK_BULLETS" "$VERSION"
import sys

template_path = sys.argv[1]
output_path = sys.argv[2]
product_name = sys.argv[3]
product_desc = sys.argv[4]
stack_bullets = sys.argv[5]
version = sys.argv[6]

with open(template_path, 'r') as f:
    template = f.read()

template = template.replace('[Your Product Name]', product_name)
template = template.replace(
    '<!-- Describe your product in 2-3 sentences. What does it do? Who is it for? -->',
    product_desc
)
template = template.replace('-\n-\n-', stack_bullets)

with open(output_path, 'r') as f:
    existing = f.read()

merged = existing.rstrip() + '\n\n---\n\n'
merged += '<!-- Ship Framework team definitions below -->\n\n'
merged += template
merged += f'\n---\n\n_Generated by [Ship Framework](https://github.com/ismailkose/ship-framework) v{version}_\n'

with open(output_path, 'w') as f:
    f.write(merged)
PYEOF
  echo -e "${GREEN}✓${RESET} Appended Ship Framework to existing CLAUDE.md"
else
  # Fresh CLAUDE.md
  python3 << 'PYEOF' - "$TEMPLATE_DIR/CLAUDE.md" "$TARGET_DIR/CLAUDE.md" "$PRODUCT_NAME" "$PRODUCT_DESC" "$STACK_BULLETS" "$VERSION"
import sys

template_path = sys.argv[1]
output_path = sys.argv[2]
product_name = sys.argv[3]
product_desc = sys.argv[4]
stack_bullets = sys.argv[5]
version = sys.argv[6]

with open(template_path, 'r') as f:
    template = f.read()

template = template.replace('[Your Product Name]', product_name)
template = template.replace(
    '<!-- Describe your product in 2-3 sentences. What does it do? Who is it for? -->',
    product_desc
)
template = template.replace('-\n-\n-', stack_bullets)
template += f'\n---\n\n_Generated by [Ship Framework](https://github.com/ismailkose/ship-framework) v{version}_\n'

with open(output_path, 'w') as f:
    f.write(template)
PYEOF
  echo -e "${GREEN}✓${RESET} Created CLAUDE.md"
fi

# ─── Copy slash commands ─────────────────────────────────────────────────────

mkdir -p "$TARGET_DIR/.claude/commands"
cp "$TEMPLATE_DIR/.claude/commands/"*.md "$TARGET_DIR/.claude/commands/"
echo -e "${GREEN}✓${RESET} Created .claude/commands/ (15 slash commands)"

# ─── Copy references ─────────────────────────────────────────────────────────

if [ -d "$TEMPLATE_DIR/references" ]; then
  mkdir -p "$TARGET_DIR/references"
  cp "$TEMPLATE_DIR/references/"*.md "$TARGET_DIR/references/"
  echo -e "${GREEN}✓${RESET} Created references/ (animation, components, UX, Apple HIG)"
fi

# ─── Copy cheatsheet ─────────────────────────────────────────────────────────

cp "$SCRIPT_DIR/CHEATSHEET.md" "$TARGET_DIR/CHEATSHEET.md"
echo -e "${GREEN}✓${RESET} Created CHEATSHEET.md"

# ─── Create TASKS.md ─────────────────────────────────────────────────────────

cat > "$TARGET_DIR/TASKS.md" << 'TASKSEOF'
# Team Task Board

> This is the team's persistent memory. /team reads this every session.
> When a task is done, move it to Completed with a date and one-line summary.
> When starting a task, mark it [IN PROGRESS] so the next session knows where we left off.

---

## Blocked (needs your decision)

<!-- Tasks that need a decision before work can continue -->

---

## Up Next (priority order)

1. [ ] Type /team to get started — it'll set up your project and figure out what to do first

---

## In Progress

<!-- Tasks currently being worked on -->

---

## Completed

<!-- Format: [date] Task name — one-line summary of what was done -->

---

## Notes

<!-- Persistent notes the team needs across sessions.
     Examples: installed dependencies, design system info, API quirks, etc. -->

TASKSEOF

echo -e "${GREEN}✓${RESET} Created TASKS.md"

# ─── Copy DECISIONS.md and CONTEXT.md templates ─────────────────────────────

if [ -f "$TEMPLATE_DIR/DECISIONS.md" ]; then
  cp "$TEMPLATE_DIR/DECISIONS.md" "$TARGET_DIR/DECISIONS.md"
  echo -e "${GREEN}✓${RESET} Created DECISIONS.md"
fi

if [ -f "$TEMPLATE_DIR/CONTEXT.md" ]; then
  cp "$TEMPLATE_DIR/CONTEXT.md" "$TARGET_DIR/CONTEXT.md"
  echo -e "${GREEN}✓${RESET} Created CONTEXT.md"
fi

# ─── Install Playwright ──────────────────────────────────────────────────────

echo ""
echo -e "${DIM}Installing Playwright for visual QA...${RESET}"

# Create package.json if it doesn't exist
if [ ! -f "$TARGET_DIR/package.json" ]; then
  echo '{ "name": "my-project", "private": true }' > "$TARGET_DIR/package.json"
fi

if (cd "$TARGET_DIR" && npm install -D @playwright/test 2>/dev/null) && \
   (cd "$TARGET_DIR" && npx playwright install chromium 2>/dev/null); then
  echo -e "${GREEN}✓${RESET} Installed Playwright — Eye and Cap can take screenshots"
else
  echo -e "${DIM}⚠ Playwright install skipped (no Node.js or network issue).${RESET}"
  echo -e "${DIM}  Add later: npm install -D @playwright/test && npx playwright install chromium${RESET}"
fi

# ─── Summary ─────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}${ORANGE}Done!${RESET} Your team is ready."
echo ""
echo "  Files created in: $TARGET_DIR"
echo "  • CLAUDE.md           — Your team framework"
echo "  • TASKS.md            — Persistent task board"
echo "  • DECISIONS.md        — Decision log"
echo "  • CONTEXT.md          — Institutional memory"
echo "  • CHEATSHEET.md       — Quick reference card"
echo "  • .claude/commands/   — 15 slash commands"
echo "  • references/         — Animation + component architecture guides"
echo ""
echo -e "${BOLD}Next step:${RESET} Open Claude Code in your project directory and type:"
echo ""
echo -e "  ${BOLD}/team I want to build [your idea]${RESET}"
echo ""
echo -e "${DIM}/team will ask for your product name, description, and tech stack on first run.${RESET}"
echo ""
